name: chat_web_app
description: A Flutter web chat application using Firebase

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  provider: ^6.0.5
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fake_cloud_firestore: ^2.4.1+1
  firebase_auth_mocks: ^0.12.0

flutter:
  uses-material-design: true
